version: "3.7"
services:
  app:
    build: .
    command: "npm run dev"
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "3738:3738"
  postgres:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    environment:
      - TZ
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    environment:
      - TZ
volumes:
  node_modules:
